# Generated by Django 2.1.3 on 2018-11-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiperris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('Apellido', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
                ('Pass', models.TextField(max_length=100)),
            ],
        ),
    ]
