# Generated by Django 2.1.3 on 2018-11-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiperris', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Pass',
            new_name='password',
        ),
    ]
