# Generated by Django 2.1.3 on 2018-11-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiperris', '0003_auto_20181125_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
